language: python
python:
  - '3.5'
  - '3.6'
before_install: cd project 
install:
  - pip install -r requirements.txt
  - pip install pytest
env:
  -TEST_DIR = tests 
script: 
  - cd $TEST_DIR && py.test
